<a href="https://colab.research.google.com/github/Kalaimurugan31/AI-in-Data-Analytics-Journey/blob/main/numpy_ai_in_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("numpy ready!")
print(np.__version__)

numpy ready!
2.0.2


In [ ]:
import numpy as np
##1d array(like a list)
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)
print(arr1.dtype)
##2d array(like a table)
arr2=np.array([[1,2,3],
      [4,5,6],
      [7,8,9]])
print(arr2)
print(arr2.shape)


[1 2 3 4 5]
(5,)
int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
print(np.zeros((3,3)))
print(np.ones((3,3)))
print(np.arange(1,10))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50])
##add five to every element
print(arr+5)
##multiply every element
print(arr*2)
##divide every element
print(arr/2)
##square every element
print(arr**2)


[15 25 35 45 55]
[ 20  40  60  80 100]
[ 5. 10. 15. 20. 25.]
[ 100  400  900 1600 2500]


In [ ]:
##math between two arrays
arr1=np.array([10,20,30,40,50])
arr2=np.array([1,2,3,4,5])
##add two arrays
print(arr1+arr2)
##multiply two arrays
print(arr1*arr2)
##subtarct two arrays
print(arr1-arr2)

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 9 18 27 36 45]


In [ ]:
##built math function
arr5=np.array([10,20,30,40,50])
print(np.sum(arr5))
print(np.mean(arr5))
print(np.min(arr5))
print(np.max(arr5))
print(np.std(arr5))

150
30.0
10
50
14.142135623730951


In [ ]:
import numpy as np
arr=([5,5,5,5,5])
print(np.array(arr))
print(np.std(arr))

[5 5 5 5 5]
0.0


In [ ]:
##class 3 Array Indexing & Slicing
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-2])

10
30
40


In [ ]:
print(arr[0:3])
print(arr[1:])
print(arr[:3])
print(arr[:-3])

[10 20 30]
[20 30 40 50]
[10 20 30]
[10 20]


In [ ]:
##2d array indexing
arr2d=np.array([[1,2,3,4,5],
               [6,7,8,9,10],
                [11,12,13,14,15]])
print(arr2d[0])
print(arr2d[1])
print(arr2d[0][0])
print(arr2d[2][2])

[1 2 3 4 5]
[ 6  7  8  9 10]
1
13


In [ ]:
import numpy as np
arr=np.arange(1,10)
print(arr)
print(arr.shape)

arr2d=arr.reshape(3,3)
print(arr2d)
print(arr2d.shape)

arr1=np.array([10,20,30,40,50,60,70,80,90,100])

arr1=arr2d.reshape(1,9)
print(arr)
print(arr.shape)

[1 2 3 4 5 6 7 8 9]
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3 4 5 6 7 8 9]
(9,)


In [ ]:
##filtering
arr5d=np.array([10,20,30,40,50,60,70,80,90])
print(arr5d[arr5d>70])
print(arr5d[arr5d<80])
print(arr5d[arr5d==80])
print(arr5d[(arr5d>=50)&(arr5d<=90)])

[80 90]
[10 20 30 40 50 60 70]
[80]
[50 60 70 80 90]


In [ ]:
##class5-numpy with pandas
import pandas as pd
import numpy as np
data={
    "name":["kalai","kesavan","vicky","kayal","saravana","nithish","anu","naveen"],
    "age":[25,30,20,23,24,23,23,24],
    "salary":[25000,30000,20000,15000,24000,23000,23000,24000]
}
df=pd.DataFrame(data)
##convert salary column to numpy
salary_arr=np.array(df["salary"])
print(salary_arr)

##calculate using numpy
print("sum:",np.sum(salary_arr))
print("mean:",np.mean(salary_arr))
print("max:",np.max(salary_arr))
print("min:",np.min(salary_arr))
print("std:",np.std(salary_arr))

##bonus
bonus=np.array([1000,5000,2000,3000,6000,4500,4000,2500])
df["total_salary"]=salary_arr+bonus
print(df)

[25000 30000 20000 15000 24000 23000 23000 24000]
sum: 184000
mean: 23000.0
max: 30000
min: 15000
std: 4000.0
       name  age  salary  total_salary
0     kalai   25   25000         26000
1   kesavan   30   30000         35000
2     vicky   20   20000         22000
3     kayal   23   15000         18000
4  saravana   24   24000         30000
5   nithish   23   23000         27500
6       anu   23   23000         27000
7    naveen   24   24000         26500
